# @formatter:off
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dan-shop.fullname" . }}
  labels:
    {{- include "dan-shop.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      targetPort: http
      port: {{ .Values.service.port }}
  selector:
    {{- include "dan-shop.selectorLabels" . | nindent 4 }}
# @formatter:on